/**
 * Tree construction for the three navigation modes.
 *
 * Knowledge  - logical categories and saved queries; nodes need not be folders.
 * Vault      - the physical folder structure exactly as Obsidian shows it.
 * Project    - one subtree per project, grouping everything associated with it.
 *
 * All three produce the same node shape so the tree component stays one
 * component rather than three, and so switching modes can preserve selection.
 */

import type { KnowledgeRecord, RecordType } from '../../domain/model/types.js';
import type { KnowledgeRepository } from '../../domain/ports/index.js';

export type TreeMode = 'knowledge' | 'vault' | 'project';

export interface TreeNode {
  readonly id: string;
  readonly label: string;
  /** What activating the node shows in the centre panel. */
  readonly kind: 'category' | 'folder' | 'record' | 'query' | 'project';
  readonly recordId: string | null;
  readonly vaultPath: string | null;
  readonly recordType: RecordType | null;
  readonly count: number;
  /** True when items may be dropped here. */
  readonly droppable: boolean;
  /** True when the app may write to the underlying location. */
  readonly writable: boolean;
  readonly badges: readonly TreeBadge[];
  readonly children: readonly TreeNode[];
}

export interface TreeBadge {
  readonly label: string;
  readonly tone: 'neutral' | 'positive' | 'caution' | 'critical' | 'info';
  /** Short glyph so the badge is not colour-only. */
  readonly glyph: string;
  readonly title: string;
}

/** The managed categories, in the order they appear in the tree. */
export const MANAGED_CATEGORIES: readonly {
  slug: string;
  label: string;
  recordTypes: readonly RecordType[];
}[] = [
  { slug: 'Inbox', label: 'Inbox', recordTypes: ['document', 'source', 'note'] },
  { slug: 'Projects', label: 'Projects', recordTypes: ['project'] },
  { slug: 'Research', label: 'Research', recordTypes: ['research_item'] },
  { slug: 'Sources', label: 'Sources', recordTypes: ['source'] },
  { slug: 'Tasks', label: 'Tasks', recordTypes: ['task'] },
  { slug: 'Decisions', label: 'Decisions', recordTypes: ['decision'] },
  { slug: 'Questions', label: 'Questions', recordTypes: ['question'] },
  { slug: 'Ideas', label: 'Ideas', recordTypes: ['idea'] },
  { slug: 'Community', label: 'Community', recordTypes: ['community_insight'] },
  { slug: 'People', label: 'People', recordTypes: ['person'] },
  { slug: 'Organizations', label: 'Organizations', recordTypes: ['organization'] },
  { slug: 'Concepts', label: 'Concepts', recordTypes: ['concept'] },
  { slug: 'Reports', label: 'Reports', recordTypes: ['report'] },
];

function recordNode(record: KnowledgeRecord): TreeNode {
  const badges: TreeBadge[] = [];
  if (record.aiGenerated) {
    badges.push({ label: 'AI', tone: 'info', glyph: '◆', title: 'Generated by a model' });
  }
  if (record.humanVerified) {
    badges.push({ label: 'Verified', tone: 'positive', glyph: '✓', title: 'Confirmed by you' });
  }
  if (record.processing === 'needs_review') {
    badges.push({ label: 'Review', tone: 'caution', glyph: '!', title: 'Awaiting your review' });
  }
  if (record.processing === 'conflict') {
    badges.push({ label: 'Conflict', tone: 'critical', glyph: '≠', title: 'Vault and database disagree' });
  }

  return {
    id: record.id,
    label: record.title,
    kind: 'record',
    recordId: record.id,
    vaultPath: record.vaultPath,
    recordType: record.recordType,
    count: 0,
    droppable: false,
    writable: record.sourceOfTruth !== 'external_read_only',
    badges,
    children: [],
  };
}

/**
 * Knowledge tree: categories are logical. A record appears under a category
 * because of its type, not because of where the file physically lives, which is
 * what lets one research item support several projects without being copied.
 */
export function buildKnowledgeTree(
  records: KnowledgeRepository,
  managedFolder = 'Agentic OS',
): TreeNode[] {
  const nodes: TreeNode[] = [];
  const CHILD_LIMIT = 200;

  for (const category of MANAGED_CATEGORIES) {
    // Count with count(), not by measuring a capped list: a category with more
    // than the page size would otherwise report the cap as its total.
    const total = records.count({ recordTypes: category.recordTypes });
    const matching = records.list({
      recordTypes: category.recordTypes,
      limit: CHILD_LIMIT,
    });
    nodes.push({
      id: `category:${category.slug}`,
      label: category.label,
      kind: 'category',
      recordId: null,
      vaultPath: `${managedFolder}/${category.slug}`,
      recordType: null,
      count: total,
      droppable: true,
      writable: true,
      badges:
        total > matching.length
          ? [
              {
                label: `showing ${matching.length}`,
                tone: 'neutral',
                glyph: '…',
                title: `Showing the ${matching.length} most recent of ${total}`,
              },
            ]
          : [],
      children: matching.map(recordNode),
    });
  }

  // Saved queries: virtual collections that exist only as a question.
  const unverifiedAi = records.list({ limit: 500 }).filter((r) => r.aiGenerated && !r.humanVerified);
  const needsReview = records.list({ limit: 500 }).filter((r) => r.processing === 'needs_review');

  nodes.push({
    id: 'query:unverified-ai',
    label: 'Unverified AI output',
    kind: 'query',
    recordId: null,
    vaultPath: null,
    recordType: null,
    count: unverifiedAi.length,
    droppable: false,
    writable: false,
    badges:
      unverifiedAi.length > 0
        ? [{ label: String(unverifiedAi.length), tone: 'info', glyph: '◆', title: 'Model output you have not confirmed' }]
        : [],
    children: unverifiedAi.slice(0, 100).map(recordNode),
  });

  nodes.push({
    id: 'query:needs-review',
    label: 'Awaiting review',
    kind: 'query',
    recordId: null,
    vaultPath: null,
    recordType: null,
    count: needsReview.length,
    droppable: false,
    writable: false,
    badges:
      needsReview.length > 0
        ? [{ label: String(needsReview.length), tone: 'caution', glyph: '!', title: 'Items awaiting your review' }]
        : [],
    children: needsReview.slice(0, 100).map(recordNode),
  });

  return nodes;
}

/**
 * Vault tree: the real folder structure. Folders outside the managed root are
 * marked non-writable so the interface can show, rather than merely promise,
 * that the application will not modify them.
 */
export function buildVaultTree(
  allRecords: readonly KnowledgeRecord[],
  managedFolder: string,
): TreeNode[] {
  interface Dir {
    name: string;
    path: string;
    dirs: Map<string, Dir>;
    files: KnowledgeRecord[];
  }

  const root: Dir = { name: '', path: '', dirs: new Map(), files: [] };

  for (const record of allRecords) {
    if (record.vaultPath === null) continue;
    const segments = record.vaultPath.split('/');
    const filename = segments.pop();
    if (filename === undefined) continue;

    let cursor = root;
    const acc: string[] = [];
    for (const segment of segments) {
      acc.push(segment);
      let next = cursor.dirs.get(segment);
      if (next === undefined) {
        next = { name: segment, path: acc.join('/'), dirs: new Map(), files: [] };
        cursor.dirs.set(segment, next);
      }
      cursor = next;
    }
    cursor.files.push(record);
  }

  const isManaged = (p: string): boolean => p === managedFolder || p.startsWith(managedFolder + '/');

  const countFiles = (dir: Dir): number =>
    dir.files.length + [...dir.dirs.values()].reduce((n, d) => n + countFiles(d), 0);

  const toNode = (dir: Dir): TreeNode => {
    const writable = isManaged(dir.path);
    const children = [
      ...[...dir.dirs.values()].sort((a, b) => a.name.localeCompare(b.name)).map(toNode),
      ...dir.files.sort((a, b) => a.title.localeCompare(b.title)).map(recordNode),
    ];
    return {
      id: `folder:${dir.path}`,
      label: dir.name,
      kind: 'folder',
      recordId: null,
      vaultPath: dir.path,
      recordType: null,
      count: countFiles(dir),
      droppable: writable,
      writable,
      badges: writable
        ? []
        : [{ label: 'Read only', tone: 'neutral', glyph: '🔒', title: 'Outside the managed folder; the app will not modify it' }],
      children,
    };
  };

  return [
    ...[...root.dirs.values()].sort((a, b) => a.name.localeCompare(b.name)).map(toNode),
    ...root.files.sort((a, b) => a.title.localeCompare(b.title)).map(recordNode),
  ];
}

/**
 * Project tree: one subtree per project, with its associated material grouped
 * by role. Association is a relationship, not a folder, so nothing is moved.
 */
export function buildProjectTree(
  records: KnowledgeRepository,
  membership: readonly { projectId: string; recordId: string; role: string }[],
): TreeNode[] {
  const projects = records.list({ recordTypes: ['project'], limit: 200 });
  const byProject = new Map<string, { recordId: string; role: string }[]>();
  for (const m of membership) {
    const list = byProject.get(m.projectId) ?? [];
    list.push({ recordId: m.recordId, role: m.role });
    byProject.set(m.projectId, list);
  }

  return projects.map((project) => {
    const members = byProject.get(project.id) ?? [];
    const byRole = new Map<string, KnowledgeRecord[]>();
    for (const member of members) {
      const record = records.get(member.recordId);
      if (record === null) continue;
      const list = byRole.get(member.role) ?? [];
      list.push(record);
      byRole.set(member.role, list);
    }

    const children: TreeNode[] = [...byRole.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([role, list]) => ({
        id: `${project.id}:${role}`,
        label: role.charAt(0).toUpperCase() + role.slice(1),
        kind: 'category' as const,
        recordId: null,
        vaultPath: null,
        recordType: null,
        count: list.length,
        droppable: true,
        writable: true,
        badges: [],
        children: list.map(recordNode),
      }));

    return {
      id: project.id,
      label: project.title,
      kind: 'project',
      recordId: project.id,
      vaultPath: project.vaultPath,
      recordType: 'project',
      count: members.length,
      // A project hub outside the managed folder is read-only, so it must not
      // advertise itself as a drop target.
      droppable: project.sourceOfTruth !== 'external_read_only',
      writable: project.sourceOfTruth !== 'external_read_only',
      badges: [],
      children,
    };
  });
}
