/**
 * Materializing records as Obsidian notes.
 *
 * The system's central promise is that knowledge survives the loss of this
 * application. A record that exists only as a database row breaks that promise,
 * so anything the app creates is written back out as plain Markdown with YAML
 * frontmatter inside the managed folder — readable in Obsidian, with no plugin.
 *
 * Only the managed folder is ever written. Notes you wrote are never touched.
 */

import { serializeFrontmatter } from '../../domain/markdown/parse.js';
import type { KnowledgeRecord } from '../../domain/model/types.js';
import { modeAllowsAppWrite } from '../../domain/model/types.js';
import type {
  AuditLogProvider,
  FileStorageProvider,
  KnowledgeRepository,
} from '../../domain/ports/index.js';

export interface MaterializeDeps {
  readonly files: FileStorageProvider;
  readonly records: KnowledgeRepository;
  readonly audit: AuditLogProvider;
  readonly managedFolder: string;
}

/**
 * Turn a title into a filename that is safe on Windows and readable in
 * Obsidian. Characters Obsidian itself forbids in links are replaced rather
 * than stripped, so the name stays recognisable.
 */
export function toNoteFilename(title: string): string {
  const cleaned = title
    .replace(/[\\/:*?"<>|#^[\]]/g, '-')
    .replace(/\s+/g, ' ')
    .replace(/-+/g, '-')
    .trim()
    .replace(/^[.-]+|[.-]+$/g, '');
  const safe = cleaned === '' ? 'Untitled' : cleaned;
  return safe.length > 100 ? safe.slice(0, 100).trimEnd() : safe;
}

/**
 * Frontmatter for a managed note.
 *
 * `agentic_id` is what makes the note survive a rename: on the next index the
 * declared id is preferred over minting a new one, so relationships hold.
 * Generated keys are grouped and named so a reader can tell at a glance which
 * metadata is the app's and which is theirs.
 */
export function managedFrontmatter(record: KnowledgeRecord): Record<string, unknown> {
  const data = record.data;
  const tags = Array.isArray(data['tags']) ? (data['tags'] as string[]) : [];

  const fm: Record<string, unknown> = {
    agentic_id: record.id,
    record_type: record.recordType,
    managed_by: 'agentic_os',
    source_of_truth: record.sourceOfTruth,
    provenance: record.provenance,
    ai_generated: record.aiGenerated,
    human_verified: record.humanVerified,
    privacy: record.privacy,
    created_at: record.createdAt,
    updated_at: record.updatedAt,
    content_hash: record.contentHash,
  };

  if (tags.length > 0) fm['tags'] = tags;

  const originalFilename = data['originalFilename'];
  if (typeof originalFilename === 'string') fm['original_filename'] = originalFilename;

  const originalPath = data['originalPath'];
  if (typeof originalPath === 'string') fm['original_file'] = originalPath;

  const dropCategory = data['dropCategory'];
  if (typeof dropCategory === 'string') fm['filed_under'] = dropCategory;

  return fm;
}

/** Render the full note body, including a provenance line a human can read. */
export function renderManagedNote(record: KnowledgeRecord): string {
  const parts: string[] = [serializeFrontmatter(managedFrontmatter(record)), ''];

  // An imported markdown file usually opens with its own H1. Emitting the title
  // again would show the heading twice in Obsidian, so only add one when the
  // body does not already lead with the same heading.
  const body = record.body ?? '';
  const leadingH1 = /^\s*#\s+(.+?)\s*$/m.exec(body.split(/\r?\n\r?\n/)[0] ?? '');
  const bodyRepeatsTitle =
    leadingH1 !== null && leadingH1[1]!.trim().toLowerCase() === record.title.trim().toLowerCase();

  if (!bodyRepeatsTitle) parts.push(`# ${record.title}`, '');

  if (record.aiGenerated) {
    parts.push(
      '> [!warning] Generated by a model',
      '> This note was written by an AI and has not been verified by a person.',
      '',
    );
  }

  const data = record.data;
  const originalFilename = data['originalFilename'];
  if (typeof originalFilename === 'string') {
    parts.push(
      `*Imported from \`${originalFilename}\`. The original file is preserved unchanged.*`,
      '',
    );
  }

  const warnings = Array.isArray(data['warnings']) ? (data['warnings'] as string[]) : [];
  if (warnings.length > 0) {
    parts.push('> [!note] Notices on import');
    for (const w of warnings) parts.push(`> - ${w}`);
    parts.push('');
  }

  if (body.trim() !== '') {
    parts.push(body.trimEnd(), '');
  } else {
    parts.push('*This item has no extracted text. The original is preserved.*', '');
  }

  return parts.join('\n');
}

export interface MaterializeResult {
  readonly written: boolean;
  readonly vaultPath: string | null;
  readonly reason: string;
}

/**
 * Write a record out as a managed note and record the path back onto it.
 * Idempotent: a record that already has a path is rewritten in place.
 */
export async function materializeRecord(
  record: KnowledgeRecord,
  deps: MaterializeDeps,
): Promise<MaterializeResult> {
  if (!modeAllowsAppWrite(record.sourceOfTruth)) {
    return {
      written: false,
      vaultPath: record.vaultPath,
      reason: `Record is ${record.sourceOfTruth}; the application does not write to it.`,
    };
  }

  const category =
    typeof record.data['dropCategory'] === 'string' ? (record.data['dropCategory'] as string) : 'Inbox';

  const targetPath =
    record.vaultPath ??
    `${deps.managedFolder}/${category}/${toNoteFilename(record.title)}.md`;

  // Defence in depth: the filesystem adapter enforces this too, but a caller
  // should never get as far as attempting a write outside the managed folder.
  if (!deps.files.isManaged(targetPath)) {
    return {
      written: false,
      vaultPath: null,
      reason: `Refused: ${targetPath} is outside the managed folder.`,
    };
  }

  // Avoid clobbering an unrelated note that happens to share a title.
  let finalPath = targetPath;
  if (record.vaultPath === null) {
    let suffix = 2;
    while (await deps.files.exists(finalPath)) {
      const existing = deps.records.getByVaultPath(finalPath);
      if (existing !== null && existing.id === record.id) break;
      finalPath = `${deps.managedFolder}/${category}/${toNoteFilename(record.title)} ${suffix}.md`;
      suffix++;
      if (suffix > 100) {
        return { written: false, vaultPath: null, reason: 'Could not find a free filename.' };
      }
    }
  }

  await deps.files.writeText(finalPath, renderManagedNote(record));

  deps.records.upsert({ ...record, vaultPath: finalPath });

  deps.audit.record({
    actor: 'system',
    action: 'note.materialize',
    targetId: record.id,
    targetPath: finalPath,
    detail: { title: record.title, category },
    undo: null,
  });

  return { written: true, vaultPath: finalPath, reason: 'Written to the managed folder.' };
}
