/**
 * Portability tests.
 *
 * The claim under test is the product's central promise: knowledge survives the
 * loss of this application. These tests destroy the database and check that an
 * imported item is still there, still readable, and still carries its identity.
 */

import { mkdtemp, mkdir, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { beforeEach, describe, expect, it } from 'vitest';
import { indexVault } from '../../src/application/indexing/indexer.js';
import { ingestDrop } from '../../src/application/ingestion/ingest.js';
import {
  materializeRecord,
  renderManagedNote,
  toNoteFilename,
} from '../../src/application/sync/materialize.js';
import { parseMarkdown } from '../../src/domain/markdown/parse.js';
import { PrivacyPolicy } from '../../src/domain/policy/privacy.js';
import { ManagedBoundaryViolation } from '../../src/domain/model/types.js';
import { openTestDatabase } from '../../src/infrastructure/db/database.js';
import {
  SqliteAuditLog,
  SqliteKnowledgeRepository,
  SqliteRelationshipRepository,
} from '../../src/infrastructure/db/repositories.js';
import { VaultFileSystem } from '../../src/infrastructure/fs/vault-filesystem.js';

const MANAGED = 'Agentic OS';
let root: string;

function makeDeps(vaultRoot: string) {
  const db = openTestDatabase();
  const files = new VaultFileSystem({
    vaultRoot,
    managedRoot: path.join(vaultRoot, MANAGED),
    internalRoot: path.join(vaultRoot, '.agentic-os'),
  });
  return {
    db,
    files,
    records: new SqliteKnowledgeRepository(db),
    relationships: new SqliteRelationshipRepository(db),
    audit: new SqliteAuditLog(db),
    privacy: new PrivacyPolicy([]),
    managedFolder: MANAGED,
  };
}

beforeEach(async () => {
  root = await mkdtemp(path.join(tmpdir(), 'agentic-mat-'));
  await mkdir(path.join(root, MANAGED, 'Research'), { recursive: true });
  await mkdir(path.join(root, 'Personal'), { recursive: true });
});

describe('toNoteFilename', () => {
  it('replaces characters that are invalid on Windows or in wikilinks', () => {
    expect(toNoteFilename('A/B:C*D?E"F<G>H|I#J^K[L]M')).not.toMatch(/[\\/:*?"<>|#^[\]]/);
  });

  it('never returns an empty name', () => {
    expect(toNoteFilename('///')).not.toBe('');
    expect(toNoteFilename('')).toBe('Untitled');
  });

  it('caps the length so the path stays within platform limits', () => {
    expect(toNoteFilename('x'.repeat(500)).length).toBeLessThanOrEqual(100);
  });
});

describe('renderManagedNote', () => {
  it('produces frontmatter a plain Markdown parser can read back', () => {
    const note = renderManagedNote({
      id: 'doc_01TEST',
      recordType: 'document',
      title: 'Test Note',
      summary: null,
      body: '# Body\n\nContent here.',
      vaultPath: null,
      contentHash: 'abc123',
      provenance: 'imported_third_party',
      sourceOfTruth: 'managed',
      privacy: 'never_external',
      processing: 'cataloged',
      confidence: null,
      humanVerified: false,
      aiGenerated: false,
      createdAt: '2026-07-21T00:00:00.000Z',
      updatedAt: '2026-07-21T00:00:00.000Z',
      archivedAt: null,
      data: { tags: ['imported'] },
    });

    const parsed = parseMarkdown(note);
    expect(parsed.hasFrontmatter).toBe(true);
    expect(parsed.frontmatter['agentic_id']).toBe('doc_01TEST');
    expect(parsed.frontmatter['managed_by']).toBe('agentic_os');
    expect(parsed.frontmatter['tags']).toEqual(['imported']);
    expect(parsed.body).toContain('Content here.');
  });

  it('labels model-written notes visibly in the body, not only in metadata', () => {
    const note = renderManagedNote({
      id: 'doc_01AI',
      recordType: 'document',
      title: 'AI Note',
      summary: null,
      body: 'Generated text.',
      vaultPath: null,
      contentHash: null,
      provenance: 'ai_generated_summary',
      sourceOfTruth: 'managed',
      privacy: 'never_external',
      processing: 'cataloged',
      confidence: 0.7,
      humanVerified: false,
      aiGenerated: true,
      createdAt: '2026-07-21T00:00:00.000Z',
      updatedAt: '2026-07-21T00:00:00.000Z',
      archivedAt: null,
      data: {},
    });
    expect(note).toMatch(/Generated by a model/i);
    expect(note).toMatch(/ai_generated: true/);
  });
});

describe('materializeRecord', () => {
  it('writes an imported item into the managed folder as Markdown', async () => {
    const deps = makeDeps(root);
    const outcome = await ingestDrop(
      {
        filename: 'paper.md',
        bytes: Buffer.from('# Findings\n\nThe result was positive.\n', 'utf8'),
        dropCategory: 'Research',
        projectId: null,
      },
      { ...deps, privacyFor: () => 'never_external' },
    );

    const record = deps.records.get(outcome.recordId!);
    const result = await materializeRecord(record!, deps);

    expect(result.written).toBe(true);
    expect(result.vaultPath).toContain(`${MANAGED}/Research/`);

    const onDisk = await readFile(path.join(root, result.vaultPath!), 'utf8');
    expect(onDisk).toContain('The result was positive.');
    expect(onDisk).toContain('agentic_id:');
  });

  it('refuses to materialize a note the user owns', async () => {
    const deps = makeDeps(root);
    const result = await materializeRecord(
      {
        id: 'note_01EXT',
        recordType: 'note',
        title: 'Theirs',
        summary: null,
        body: 'x',
        vaultPath: 'Personal/theirs.md',
        contentHash: null,
        provenance: 'imported_obsidian_note',
        sourceOfTruth: 'external_read_only',
        privacy: 'never_external',
        processing: 'cataloged',
        confidence: null,
        humanVerified: false,
        aiGenerated: false,
        createdAt: '2026-07-21T00:00:00.000Z',
        updatedAt: '2026-07-21T00:00:00.000Z',
        archivedAt: null,
        data: {},
      },
      deps,
    );
    expect(result.written).toBe(false);
    expect(result.reason).toMatch(/external_read_only/);
  });

  it('does not overwrite a different note that shares a title', async () => {
    const deps = makeDeps(root);
    await deps.files.writeText(`${MANAGED}/Research/Findings.md`, '# Pre-existing\n');

    const outcome = await ingestDrop(
      {
        filename: 'x.md',
        bytes: Buffer.from('# Findings\n\nNew content.\n', 'utf8'),
        dropCategory: 'Research',
        projectId: null,
      },
      { ...deps, privacyFor: () => 'never_external' },
    );
    const record = deps.records.get(outcome.recordId!);
    const result = await materializeRecord(record!, deps);

    expect(result.vaultPath).not.toBe(`${MANAGED}/Research/Findings.md`);
    const original = await readFile(path.join(root, MANAGED, 'Research', 'Findings.md'), 'utf8');
    expect(original).toBe('# Pre-existing\n');
  });

  it('is idempotent: materializing twice rewrites in place', async () => {
    const deps = makeDeps(root);
    const outcome = await ingestDrop(
      {
        filename: 'note.md',
        bytes: Buffer.from('# Once\n', 'utf8'),
        dropCategory: 'Research',
        projectId: null,
      },
      { ...deps, privacyFor: () => 'never_external' },
    );
    const record = deps.records.get(outcome.recordId!);
    const first = await materializeRecord(record!, deps);
    const reloaded = deps.records.get(outcome.recordId!);
    const second = await materializeRecord(reloaded!, deps);

    expect(second.vaultPath).toBe(first.vaultPath);
  });
});

describe('surviving the loss of the database', () => {
  it('an imported item is still readable and keeps its identity after a full rebuild', async () => {
    // Import and materialize.
    const first = makeDeps(root);
    const outcome = await ingestDrop(
      {
        filename: 'important.md',
        bytes: Buffer.from('# Important\n\nDo not lose this.\n', 'utf8'),
        dropCategory: 'Research',
        projectId: null,
      },
      { ...first, privacyFor: () => 'never_external' },
    );
    const record = first.records.get(outcome.recordId!);
    const materialized = await materializeRecord(record!, first);
    const originalId = record!.id;

    // Throw the entire database away.
    const second = makeDeps(root);
    expect(second.records.count({})).toBe(0);

    // Rebuild from the vault alone.
    await indexVault(second);

    const recovered = second.records.getByVaultPath(materialized.vaultPath!);
    expect(recovered).not.toBeNull();
    expect(recovered!.body).toContain('Do not lose this.');
    // The id was pinned into frontmatter, so relationships would survive too.
    expect(recovered!.id).toBe(originalId);
  });

  it('the materialized note is plain Markdown requiring no plugin', async () => {
    const deps = makeDeps(root);
    const outcome = await ingestDrop(
      {
        filename: 'plain.md',
        bytes: Buffer.from('# Plain\n\nJust text.\n', 'utf8'),
        dropCategory: 'Research',
        projectId: null,
      },
      { ...deps, privacyFor: () => 'never_external' },
    );
    const record = deps.records.get(outcome.recordId!);
    const result = await materializeRecord(record!, deps);
    const text = await readFile(path.join(root, result.vaultPath!), 'utf8');

    // Opens with a standard YAML fence and contains no proprietary syntax.
    expect(text.startsWith('---\n')).toBe(true);
    expect(text).toContain('# Plain');
    expect(text).not.toMatch(/```dataview/);
  });
});

describe('the write boundary holds under materialization', () => {
  it('a record claiming an outside path is refused by the filesystem adapter', async () => {
    const deps = makeDeps(root);
    await expect(
      deps.files.writeText('Personal/evil.md', 'should not be written'),
    ).rejects.toBeInstanceOf(ManagedBoundaryViolation);
  });
});

describe('heading handling', () => {
  it('does not repeat the title when the imported body already leads with it', () => {
    const note = renderManagedNote({
      id: 'doc_01H1',
      recordType: 'document',
      title: 'My Note',
      summary: null,
      body: '# My Note\n\nBody text.',
      vaultPath: null,
      contentHash: null,
      provenance: 'imported_third_party',
      sourceOfTruth: 'managed',
      privacy: 'never_external',
      processing: 'cataloged',
      confidence: null,
      humanVerified: false,
      aiGenerated: false,
      createdAt: '2026-07-21T00:00:00.000Z',
      updatedAt: '2026-07-21T00:00:00.000Z',
      archivedAt: null,
      data: {},
    });
    expect(note.match(/^# My Note$/gm)).toHaveLength(1);
  });

  it('adds a title heading when the body has none', () => {
    const note = renderManagedNote({
      id: 'doc_01H2',
      recordType: 'document',
      title: 'Untitled Body',
      summary: null,
      body: 'Just a paragraph with no heading.',
      vaultPath: null,
      contentHash: null,
      provenance: 'imported_third_party',
      sourceOfTruth: 'managed',
      privacy: 'never_external',
      processing: 'cataloged',
      confidence: null,
      humanVerified: false,
      aiGenerated: false,
      createdAt: '2026-07-21T00:00:00.000Z',
      updatedAt: '2026-07-21T00:00:00.000Z',
      archivedAt: null,
      data: {},
    });
    expect(note).toMatch(/^# Untitled Body$/m);
  });
});
